# Web Scraping

In [1]:
import requests 
import re
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "accept-encoding":"gzip, deflate, br, zstd",
    "content-type":"text/plain;charset=UTF-8",
    "accept-language":"en-US,en;q=0.9"

}

In [3]:
url = "https://www.flipkart.com/search?q=bikes%20&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
response = requests.get(url,headers = headers)

In [4]:
print(response.status_code)

200

In [5]:
html_data = response.text
soup = BeautifulSoup(html_data)

In [6]:
name = soup.find_all("div",class_ = "RG5Slk")

In [7]:
product_name = []
for i in name:
    product_name.append(i.text)

In [8]:
(product_name)

['Chetak C3503 Electric Scooter by Bajaj Auto Booking for Ex-Showroom Price (with Portable Charger, Matt...',
 'Chetak C3503 Electric Scooter by Bajaj Auto Booking for Ex-Showroom Price (with Portable Charger, Indi...',
 'Yezdi Roadster Booking for Ex-Showroom Price',
 'TVS XL100 Booking for Ex-Showroom Price',
 'TVS XL100 Booking for Ex-Showroom Price',
 'Hero Splendor+ Non i3S Booking for Ex-Showroom Price',
 'TVS Sport (ES+) Booking for Ex-Showroom Price',
 'TVS Sport (ES) Booking for Ex-Showroom Price',
 'Ather Rizta S 123 KM Booking for Ex-Showroom Price (with Portable Charger, Siachen White Mono)',
 'TVS Radeon (Digi Edition) Booking for Ex-Showroom Price',
 'Hero HF Deluxe Non i3S-Kick Booking for Ex-Showroom Price',
 'Chetak C3502 Electric Scooter by Bajaj Auto Booking for Ex-Showroom Price (with Portable Charger, Indi...',
 'TVS Radeon All Black Edition Booking for Ex-Showroom Price',
 'TVS Radeon (Base Edition) Booking for Ex-Showroom Price',
 'TVS Radeon (Digi Edition) Booking for Ex-Showroom Price',
 'VIDA VX2 PLUS 4.4 kWh Booking for Ex-Showroom Price (with Portable Charger, Pearl Red)',
 'Hero Xtreme Booking for Ex-Showroom Price',
 'Hero Destini 125 ZX+ Booking for Ex-Showroom Price',
 'VIDA VX2 PLUS 4.4 kWh Booking for Ex-Showroom Price (with Portable Charger, Matt Giallo Lime)',
 'VIDA VX2 PLUS 4.4 kWh Booking for Ex-Showroom Price (with Portable Charger, Matt Gun Metal Grey)',
 'Hero Xtreme Booking for Ex-Showroom Price',
 'Hero HF Deluxe Non i3S-Kick Booking for Ex-Showroom Price',
 'VIDA VX2 PLUS 4.4 kWh Booking for Ex-Showroom Price (with Portable Charger, Pearl Black)',
 'VIDA VX2 PLUS 4.4 kWh Booking for Ex-Showroom Price (with Portable Charger, Nexus Blue Matt)']

In [9]:
name = soup.find_all("div",class_ = "CMXw7N")

In [10]:
product_name = []
for i in name:
    product_name.append(i.text)

In [11]:
product_name

['Range: 151 kmMaximum Speed: 70 kmphCharging Time: 5 hrTire Type: TubelessColoured LCD DisplayChetak offers a warranty of 50000 km or 3 year (whichever comes earlier) on the product and the Lithium-ion battery. Warranty is effective from the date of the Chetak sales invoice and is in effect as long as periodic maintenance services are done at Chetak authorised service centres, as per recommended schedules.',
 'Range: 151 kmMaximum Speed: 70 kmphCharging Time: 5 hrTire Type: TubelessColoured LCD DisplayChetak offers a warranty of 50000 km or 3 year (whichever comes earlier) on the product and the Lithium-ion battery. Warranty is effective from the date of the Chetak sales invoice and is in effect as long as periodic maintenance services are done at Chetak authorised service centres, as per recommended schedules.',
 'Maximum Power: 21.46 @7500 rpmEngine Capacity: 334 ccBrake Front: DiscTire Type: TubelessConsole Feature: Speedometer - LCD4 Years or 50,000 Km',
 'Engine Capacity: 99.7 ccBrake Front: DrumTire Type: TubedConsole Feature: AnalogDuring 3 Years from the date of purchase or during the first 36,000 km of run for the vehicle in the hands of original retail purchaser, whichever is earlier."',
 'Engine Capacity: 99.7 ccBrake Front: DrumTire Type: TubedConsole Feature: AnalogDuring 3 Years from the date of purchase or during the first 36,000 km of run for the vehicle in the hands of original retail purchaser, whichever is earlier."',
 'Maximum Power: 5.9 kW @ 8000 rpmEngine Capacity: 97.2 ccBrake Front: DrumTire Type: TubelessConsole Feature: Analogue speedometerHero MotoCorp warrants all its motorcycles for a period of 5 years or 70000 Km and scooters for a period of 5 years or 50000 Km, whichever is earlier, from the date of purchase.',
 'Maximum Power: 8.18 bhp @ 7,350 rpmEngine Capacity: 109.7 ccBrake Front: DrumTire Type: TubedConsole Feature: AnalogueWhile the Company has taken every care to maintain quality in the manufacture of the TVS Sport, the above saidwarranty is subject to other terms of warranty: During 5 Years from the date of purchase or during the first 60,000 km of run for the vehicle in the hands of originalretail purchaser, whichever is earlier, the parts of the vehicle covered under warranty which prove to the satisfactionof the Company to have a manufacturing defect will be repaired or replaced free of cost.',
 'Maximum Power: 8.18 bhp @ 7,350 rpmEngine Capacity: 109.7 ccBrake Front: DrumTire Type: TubedConsole Feature: AnalogueDuring 5 Years from the date of purchase or during the first 60,000 km of run for the vehicle in the hands of original retail purchaser, whichever is earlier, the parts of the vehicle covered under warranty which prove to the satisfaction of the Company to have a manufacturing defect will be repaired or replaced free of cost.',
 'Range: 123 kmMaximum Speed: 80 kmphCharging Time: 7.45 HrsTire Type: TubelessBattery: 3 Years/ 30000 Km, Vehicle: 3 Years/ 30000 Km',
 'Maximum Power: 8.18 bhp (at 7350 RPM)Engine Capacity: 109.7 ccBrake Front: DrumTire Type: TubelessConsole Feature: Speedometer: Digital Odometer: DigitalDuring 5 Years from the date of purchase or during the first 60,000 km of run for the vehicle in the hands of original retail purchaser, whichever is earlier, the parts of the vehicle covered under warranty which prove to the satisfaction of the Company to have a manufacturing defect will be repaired or replaced free of cost.',
 'Maximum Power: 7.91Engine Capacity: 97.2 ccBrake Front: DrumTire Type: TubedConsole Feature: SpeedometerHero MotoCorp warrants all its motorcycles for a period of 5 years or 70000 Km and scooters for a period of 5 years or 50000 Km, whichever is earlier, from the date of purchase.',
 'Range: 153 kmMaximum Speed: 80 KmphCharging Time: 5 hrTire Type: TubelessChetak offers a warranty of 50000 km or 3 year (whichever comes earlier) on the product and the Lithium-ion battery. The auxillary battery has a warranty of 18 months and tyres have a warranty of 12 months. Warranty is effective from the date of the Chetak sales invoice and is in effect as long as periodic maintenance services are done at Chetak authorised service centres, as per recommended schedules.',
 'Maximum Power: 8.18 bhp @7350 RPMEngine Capacity: 109.7 ccBrake Front: DrumTire Type: TubelessConsole Feature: Speedometer: Analogue Odometer: DigitalWhile the Company has taken every care to maintain quality in the manufacture of the TVS Sport, the above saidwarranty is subject to other terms of warranty: During 5 Years from the date of purchase or during the first 60,000 km of run for the vehicle in the hands of originalretail purchaser, whichever is earlier, the parts of the vehicle covered under warranty which prove to the satisfactionof the Company to have a manufacturing defect will be repaired or replaced free of cost.',
 'Maximum Power: 8.18 bhp (at 7350 RPM)Engine Capacity: 109.7 ccBrake Front: DrumTire Type: TubelessConsole Feature: Speedometer: Analogue Odometer: DigitalDuring 5 Years from the date of purchase or during the first 60,000 km of run for the vehicle in the hands of original retail purchaser, whichever is earlier, the parts of the vehicle covered under warranty which prove to the satisfaction of the Company to have a manufacturing defect will be repaired or replaced free of cost.',
 'Maximum Power: 8.18 bhp (at 7350 RPM)Engine Capacity: 109.7 ccBrake Front: DrumTire Type: TubelessConsole Feature: Speedometer: Digital Odometer: DigitalDuring 5 Years from the date of purchase or during the first 60,000 km of run for the vehicle in the hands of original retail purchaser, whichever is earlier, the parts of the vehicle covered under warranty which prove to the satisfaction of the Company to have a manufacturing defect will be repaired or replaced free of cost.',
 'Range: 187 kmMaximum Speed: 90 km/hCharging Time: 3.17 HrTire Type: TubelessIt comes with an overall warranty of 5 years or 50,000 KMs, whichever is earlier. The battery pack comes with a warranty of 3 years or 30,000 KMs, whichever is earlier.',
 'Maximum Power: 16.9 PS (at 8500 RPM)Engine Capacity: 163.2 ccBrake Front: DiscTire Type: TubelessConsole Feature: Inverted LCD ConsoleHero MotoCorp warrants all its motorcycles for a period of 5 years or 70000 Km and scooters for a period of 5 years or 50000 Km, whichever is earlier, from the date of purchase.',
 'Engine Capacity: 124.6 ccBrake Front: DiscTire Type: TubelessConsole Feature: Fully Digital SpeedometerHero MotoCorp warrants all its motorcycles for a period of 5 years or 70000 Km and scooters for a period of 5 years or 50000 Km, whichever is earlier, from the date of purchase.',
 'Range: 187 kmMaximum Speed: 90 km/hCharging Time: 3.17 HrTire Type: TubelessIt comes with an overall warranty of 5 years or 50,000 KMs, whichever is earlier. The battery pack comes with a warranty of 3 years or 30,000 KMs, whichever is earlier.',
 'Range: 187 kmMaximum Speed: 90 km/hCharging Time: 3.17 HrTire Type: TubelessIt comes with an overall warranty of 5 years or 50,000 KMs, whichever is earlier. The battery pack comes with a warranty of 3 years or 30,000 KMs, whichever is earlier.',
 'Maximum Power: 15.2Engine Capacity: 163 ccBrake Front: DiscTire Type: TubelessConsole Feature: SpeedometerHero MotoCorp warrants all its motorcycles for a period of 5 years or 70000 Km and scooters for a period of 5 years or 50000 Km, whichever is earlier, from the date of purchase.',
 'Maximum Power: 7.91Engine Capacity: 97.2 ccBrake Front: DrumTire Type: TubedConsole Feature: SpeedometerHero MotoCorp warrants all its motorcycles for a period of 5 years or 70000 Km and scooters for a period of 5 years or 50000 Km, whichever is earlier, from the date of purchase.',
 'Range: 187 kmMaximum Speed: 90 km/hCharging Time: 3.17 HrTire Type: TubelessIt comes with an overall warranty of 5 years or 50,000 KMs, whichever is earlier. The battery pack comes with a warranty of 3 years or 30,000 KMs, whichever is earlier.',
 'Range: 187 kmMaximum Speed: 90 km/hCharging Time: 3.17 HrTire Type: TubelessIt comes with an overall warranty of 5 years or 50,000 KMs, whichever is earlier. The battery pack comes with a warranty of 3 years or 30,000 KMs, whichever is earlier.']

In [12]:
name = soup.find_all("div", class_="CMXw7N")

product_name = []

for i in name:
    product_name.append(i.text)

In [13]:
spec = soup.find_all("div", class_="CMXw7N")

specifications = []

for i in spec:
    specifications.append(i.text)

In [14]:
price = soup.find_all("div",class_="hZ3P6w DeU9vF")

price_list = []
for i in price:
    price_list.append(i.text)

In [15]:
rating = soup.find_all("div",class_="MKiFS6")

rating_list = []
for i in rating:
    rating_list.append(i.text)

In [16]:
print(len(product_name))
print(len(specifications))
print(len(price_list))
print(len(rating_list))

24
24
24
33

In [17]:
min_len=min(len(product_name),
            len(specifications),
            len(price_list),
            len(rating_list))
min_len

24

In [18]:
import pandas as pd

df = pd.DataFrame({
    "Product_Name": product_name[:min_len],
    "Specifications": specifications[:min_len],
    "Price": price_list[:min_len],
    "Rating":rating_list[:min_len]
})

df.head()

,Product_Name,Specifications,Price,Rating
0,Range: 151 kmMaximum Speed: 70 kmphCharging Ti...,Range: 151 kmMaximum Speed: 70 kmphCharging Ti...,"₹1,24,157",4.4
1,Range: 151 kmMaximum Speed: 70 kmphCharging Ti...,Range: 151 kmMaximum Speed: 70 kmphCharging Ti...,"₹1,29,157",4.4
2,Maximum Power: 21.46 @7500 rpmEngine Capacity:...,Maximum Power: 21.46 @7500 rpmEngine Capacity:...,"₹2,14,969",4.5
3,Engine Capacity: 99.7 ccBrake Front: DrumTire ...,Engine Capacity: 99.7 ccBrake Front: DrumTire ...,"₹57,960",4.5
4,Engine Capacity: 99.7 ccBrake Front: DrumTire ...,Engine Capacity: 99.7 ccBrake Front: DrumTire ...,"₹60,480",4.5

In [19]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

all_names = []
all_specs = []
all_price = []
all_ratings = []
No_of_ratings = []
No_of_reviews = []

for page in range(1, 30):

    url = f"https://www.flipkart.com/search?q=bikes&page={page}"

    response = requests.get(url, headers=headers)

    print(page, response.status_code)

    soup = BeautifulSoup(response.text, "html.parser")

    # Product Name
    names = soup.find_all("div", class_="RG5Slk")

    # Specifications
    specs = soup.find_all("div", class_="CMXw7N")

    # price 
    price = soup.find_all("div",class_="hZ3P6w DeU9vF")

    # Rating 
    rating = soup.find_all("div",class_="MKiFS6")

    # No of Ratings
    ratings_no = soup.find_all("span",class_="PvbNMB")

    # No of Reviews
    reviews_no = soup.find_all("span",class_="PvbNMB")

    for n in names:
        all_names.append(n.text.strip())

    for s in specs:
        all_specs.append(s.text.strip())
    for p in price:
        all_price.append(p.text.strip())
    for r in rating:
        all_ratings.append(r.text.strip())
    for nr in ratings_no:
        No_of_ratings.append(nr.text.strip())
    for nre in reviews_no:
        No_of_reviews.append(nre.text.strip())

1 200
2 200
3 200
4 200
5 200
6 200
7 200
8 200
9 200
10 200
11 200
12 200
13 200
14 200
15 200
16 200
17 200
18 200
19 200
20 200
21 200
22 200
23 200
24 200
25 200
26 200
27 200
28 200
29 200

In [20]:
print(len(all_names))
print(len(all_specs))
print(len(all_price))
print(len(all_ratings))
print(len(No_of_reviews))
print(len(No_of_ratings))

645
645
645
963
558
558

In [21]:
min_len=min(len(all_names),
            len(all_specs),
            len(all_price),
            len(all_ratings),
            len(No_of_ratings),
            len(No_of_reviews))
min_len

558

In [22]:
all_names = all_names[:min_len]
all_specs = all_specs[:min_len]
all_price = all_price[:min_len]
all_ratings = all_ratings[:min_len]
No_of_ratings = No_of_ratings[:min_len]
No_of_reviews = No_of_reviews[:min_len]

In [23]:
import pandas as pd

df = pd.DataFrame({
    "Product_Name": all_names,
    "Specifications": all_specs,
    "Price": all_price,
    "Rating": all_ratings,
    "No_of_Ratings": No_of_ratings,
    "No_of_Reviews": No_of_reviews
})

In [24]:
df.head()

,Product_Name,Specifications,Price,Rating,No_of_Ratings,No_of_Reviews
0,TVS Zest Booking for Ex-Showroom Price,Engine Capacity: 109.7 ccBrake Front: DrumTire...,"₹78,550",4.5,359 Ratings & 38 Reviews,359 Ratings & 38 Reviews
1,Chetak C3503 Electric Scooter by Bajaj Auto Bo...,Range: 151 kmMaximum Speed: 70 kmphCharging Ti...,"₹1,24,157",4.4,"2,178 Ratings & 210 Reviews","2,178 Ratings & 210 Reviews"
2,Yezdi Roadster Booking for Ex-Showroom Price,Maximum Power: 21.46 @7500 rpmEngine Capacity:...,"₹2,14,969",4.5,458 Ratings & 58 Reviews,458 Ratings & 58 Reviews
3,Yezdi Scrambler Booking for Ex-Showroom Price,Maximum Power: 22.05 kw@8100 r/min (30PS)Engin...,"₹2,00,969",4.5,"5,032 Ratings & 486 Reviews","5,032 Ratings & 486 Reviews"
4,TVS XL100 Booking for Ex-Showroom Price,Engine Capacity: 99.7 ccBrake Front: DrumTire ...,"₹60,480",4.5,458 Ratings & 58 Reviews,458 Ratings & 58 Reviews

In [25]:
df["Maximum_Power"] = df["Specifications"].str.extract(
    r"Maximum Power:\s*(.*?)(?=Engine Capacity:|Brake Front:|Range:|$)"
)

In [26]:
df["Engine_Capacity"] = df["Specifications"].str.extract(
    r"Engine Capacity:\s*(.*?)(?=Brake Front:|Tire Type:|Console Feature:|$)"
)

In [27]:
df["Brake_Front"] = df["Specifications"].str.extract(
    r"Brake Front:\s*(.*?)(?=Tire Type:|Console Feature:|$)"
)

In [28]:
df["Tire_Type"] = df["Specifications"].str.extract(
    r"Tire Type:\s*(.*?)(?=Console Feature:|During|$)"
)

In [29]:
df["Console_Feature"] = df["Specifications"].str.extract(
    r"Console Feature:\s*(.*?)(?=During|Warranty|$)"
)

In [30]:
df["Range"] = df["Specifications"].str.extract(
    r"Range:\s*(.*?)(?=Maximum Speed:|Charging Time:|$)"
)

In [31]:
df["Maximum_Speed"] = df["Specifications"].str.extract(
    r"Maximum Speed:\s*(.*?)(?=Charging Time:|Tire Type:|$)"
)

In [32]:
df["Charging_Time"] = df["Specifications"].str.extract(
    r"Charging Time:\s*(.*?)(?=Tire Type:|$)"
)

In [33]:
brands = [
    "Hero","Honda","TVS","Yamaha","Bajaj",
    "Royal Enfield","KTM","Suzuki","Ather",
    "VIDA","Yezdi","Chetak"
]

def get_brand(name):
    for brand in brands:
        if brand.lower() in name.lower():
            return brand
    return "Other"

df["Brand"] = df["Product_Name"].apply(get_brand)

In [34]:
def bike_type(name):
    name = name.lower()

    if "electric" in name:
        return "Electric"

    elif "scooter" in name:
        return "Scooter"

    else:
        return "Motorcycle"

df["Bike_Type"] = df["Product_Name"].apply(bike_type)

In [35]:
df.head()

,Product_Name,Specifications,Price,Rating,No_of_Ratings,No_of_Reviews,Maximum_Power,Engine_Capacity,Brake_Front,Tire_Type,Console_Feature,Range,Maximum_Speed,Charging_Time,Brand,Bike_Type
0,TVS Zest Booking for Ex-Showroom Price,Engine Capacity: 109.7 ccBrake Front: DrumTire...,"₹78,550",4.5,359 Ratings & 38 Reviews,359 Ratings & 38 Reviews,NaN,109.7 cc,Drum,TubelessUnder Seat Storage: 19 L,Analog SpeedometerWhile the Company has taken ...,NaN,NaN,NaN,TVS,Motorcycle
1,Chetak C3503 Electric Scooter by Bajaj Auto Bo...,Range: 151 kmMaximum Speed: 70 kmphCharging Ti...,"₹1,24,157",4.4,"2,178 Ratings & 210 Reviews","2,178 Ratings & 210 Reviews",NaN,NaN,NaN,TubelessColoured LCD DisplayChetak offers a wa...,NaN,151 km,70 kmph,5 hr,Bajaj,Electric
2,Yezdi Roadster Booking for Ex-Showroom Price,Maximum Power: 21.46 @7500 rpmEngine Capacity:...,"₹2,14,969",4.5,458 Ratings & 58 Reviews,458 Ratings & 58 Reviews,21.46 @7500 rpm,334 cc,Disc,Tubeless,"Speedometer - LCD4 Years or 50,000 Km",NaN,NaN,NaN,Yezdi,Motorcycle
3,Yezdi Scrambler Booking for Ex-Showroom Price,Maximum Power: 22.05 kw@8100 r/min (30PS)Engin...,"₹2,00,969",4.5,"5,032 Ratings & 486 Reviews","5,032 Ratings & 486 Reviews",22.05 kw@8100 r/min (30PS),334 cc,Disc,Tubed,Speedometer - LCD,NaN,NaN,NaN,Yezdi,Motorcycle
4,TVS XL100 Booking for Ex-Showroom Price,Engine Capacity: 99.7 ccBrake Front: DrumTire ...,"₹60,480",4.5,458 Ratings & 58 Reviews,458 Ratings & 58 Reviews,NaN,99.7 cc,Drum,Tubed,Analog,NaN,NaN,NaN,TVS,Motorcycle

In [36]:
df.rename(columns={
    "Price": "Price_INR",
    "No_of_Ratings": "Total_Ratings",
    "No_of_Reviews": "Total_Reviews",
    "Engine_Capacity": "Engine_Capacity_CC",
    "Brake_Front": "Front_Brake",
    "Range": "Range_KM",
    "Maximum_Speed": "Maximum_Speed_KMPH",
    "Console_Feature": "Console_Type"
}, inplace=True)

In [37]:
df = df[
    [
        "Product_Name",
        "Brand",
        "Bike_Type",
        "Price_INR",
        "Rating",
        "Total_Ratings",
        "Total_Reviews",
        "Engine_Capacity_CC",
        "Maximum_Power",
        "Range_KM",
        "Maximum_Speed_KMPH",
        "Charging_Time",
        "Front_Brake",
        "Tire_Type",
        "Console_Type"
    ]
]

In [38]:
df.head()

,Product_Name,Brand,Bike_Type,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Maximum_Power,Range_KM,Maximum_Speed_KMPH,Charging_Time,Front_Brake,Tire_Type,Console_Type
0,TVS Zest Booking for Ex-Showroom Price,TVS,Motorcycle,"₹78,550",4.5,359 Ratings & 38 Reviews,359 Ratings & 38 Reviews,109.7 cc,NaN,NaN,NaN,NaN,Drum,TubelessUnder Seat Storage: 19 L,Analog SpeedometerWhile the Company has taken ...
1,Chetak C3503 Electric Scooter by Bajaj Auto Bo...,Bajaj,Electric,"₹1,24,157",4.4,"2,178 Ratings & 210 Reviews","2,178 Ratings & 210 Reviews",NaN,NaN,151 km,70 kmph,5 hr,NaN,TubelessColoured LCD DisplayChetak offers a wa...,NaN
2,Yezdi Roadster Booking for Ex-Showroom Price,Yezdi,Motorcycle,"₹2,14,969",4.5,458 Ratings & 58 Reviews,458 Ratings & 58 Reviews,334 cc,21.46 @7500 rpm,NaN,NaN,NaN,Disc,Tubeless,"Speedometer - LCD4 Years or 50,000 Km"
3,Yezdi Scrambler Booking for Ex-Showroom Price,Yezdi,Motorcycle,"₹2,00,969",4.5,"5,032 Ratings & 486 Reviews","5,032 Ratings & 486 Reviews",334 cc,22.05 kw@8100 r/min (30PS),NaN,NaN,NaN,Disc,Tubed,Speedometer - LCD
4,TVS XL100 Booking for Ex-Showroom Price,TVS,Motorcycle,"₹60,480",4.5,458 Ratings & 58 Reviews,458 Ratings & 58 Reviews,99.7 cc,NaN,NaN,NaN,NaN,Drum,Tubed,Analog

In [39]:
df["Product_Name"] = (
    df["Product_Name"]
    .str.replace("Booking for Ex-Showroom Price", "", regex=False)
    .str.replace("by Bajaj Auto", "", regex=False)
    .str.replace(r"\(.*?\)", "", regex=True)   # Remove everything inside ()
    .str.replace(r"\.\.\.", "", regex=True)    # Remove ...
    .str.replace(r"\s+", " ", regex=True)      # Remove extra spaces
    .str.strip()
)

In [40]:
df["Product_Name"] = df["Product_Name"].str.replace(
    r"\(.*", "", regex=True
)

In [41]:
df["Product_Name"] = df["Product_Name"].str.replace(
    "...", "", regex=False
)

In [42]:
df["Product_Name"] = df["Product_Name"].str.strip()

In [43]:
df["Product_Name"].sample(20)

116                      Hero Xtreme
143                 Joy e-bike Mihos
31     Chetak C3502 Electric Scooter
485         ROYAL ENFIELD Bullet 350
384               Kinetic Green Zing
253             BGauss C12i EX Gen 2
135            Green Sunny Blue 40KM
39                Kinetic Green Zing
296           Hero Splendor+ Non i3S
185                   TVS RAIDER iGO
204         Green Invicta White 60KM
127               Hero Splendor+ i3S
452             TVS iQube ST 5.1 kWh
445         Hero Splendor+ Flex Fuel
277                      Hero Xtreme
394                     Hero XOOM VX
206                      Hero Xtreme
309        BGauss C12i MAX 2.0 Gen 2
239               BGauss C12 MAX 2.0
104                TVS iQube 2.2 kWh
Name: Product_Name, dtype: object

In [44]:
def clean_product_name(row):
    name = row["Product_Name"]
    brand = row["Brand"]

    if pd.notna(name) and pd.notna(brand):
        if name.lower().startswith(brand.lower()):
            name = name[len(brand):].strip()

    return name

df["Product_Name"] = df.apply(clean_product_name, axis=1)

In [45]:
df.head(100).sample(5)

,Product_Name,Brand,Bike_Type,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Maximum_Power,Range_KM,Maximum_Speed_KMPH,Charging_Time,Front_Brake,Tire_Type,Console_Type
17,Chetak C3503 Electric Scooter,Bajaj,Electric,"₹1,29,157",4.5,"11,869 Ratings & 1,205 Reviews","11,869 Ratings & 1,205 Reviews",NaN,NaN,151 km,70 kmph,5 hr,NaN,TubelessColoured LCD DisplayChetak offers a wa...,NaN
95,Apache RTR 160,TVS,Motorcycle,"₹1,21,690",4.7,"2,178 Ratings & 210 Reviews","2,178 Ratings & 210 Reviews",160 cc,15.8 bhp (at 8750 RPM),NaN,NaN,NaN,Disc,Tubeless,Speedometer LCD
37,Super Splendor XTEC 2.0,Hero,Motorcycle,"₹86,000",4.5,36 Ratings & 4 Reviews,36 Ratings & 4 Reviews,124.7 cc,10.7 BHP@7500 rpm,NaN,NaN,NaN,Disc,Tubeless,NaN
10,Splendor+ Non i3S,Hero,Motorcycle,"₹77,349",4.4,"2,504 Ratings & 301 Reviews","2,504 Ratings & 301 Reviews",97.2 cc,5.9 kW @ 8000 rpm,NaN,NaN,NaN,Drum,Tubeless,Analogue speedometerHero MotoCorp warrants all...
94,Apache RTR 160,TVS,Motorcycle,"₹1,19,590",4.5,"11,869 Ratings & 1,205 Reviews","11,869 Ratings & 1,205 Reviews",160 cc,15.8 bhp (at 8750 RPM),NaN,NaN,NaN,Disc,Tubeless,Speedometer LCD

In [46]:
df = df.reset_index(drop=True)
# if it's an actual column named 'Unnamed: 0' or similar:
df = df.drop(columns=[c for c in df.columns if 'Unnamed' in c], errors='ignore')

In [47]:
df['Price_INR'] = (
    df['Price_INR']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
    .astype(float)
)

In [48]:
extracted = df['Total_Ratings'].astype(str).str.extract(
    r'([\d,]+)\s*Ratings?\s*&\s*([\d,]+)\s*Reviews?'
)
df['Total_Ratings'] = extracted[0].str.replace(',', '', regex=False).astype(float)
df['Total_Reviews'] = extracted[1].str.replace(',', '', regex=False).astype(float)

In [49]:
df['Engine_Capacity_CC'] = (
    df['Engine_Capacity_CC'].astype(str).str.extract(r'([\d.]+)').astype(float)
)

In [50]:
df['Power_bhp'] = df['Maximum_Power'].astype(str).str.extract(r'([\d.]+)\s*bhp')[0].astype(float)
df['Power_kW'] = df['Maximum_Power'].astype(str).str.extract(r'([\d.]+)\s*kW')[0].astype(float)
# convert kW rows to bhp for a single unified column (1 kW = 1.341 bhp)
df['Power_bhp'] = df['Power_bhp'].fillna(df['Power_kW'] * 1.341)
df['RPM'] = df['Maximum_Power'].astype(str).str.extract(r'@\s*([\d,]+)\s*rpm', flags=2)[0].str.replace(',', '')

In [51]:
df['Range_KM'] = df['Range_KM'].astype(str).str.extract(r'([\d.]+)').astype(float)
df['Maximum_Speed_KMPH'] = df['Maximum_Speed_KMPH'].astype(str).str.extract(r'([\d.]+)').astype(float)
df['Charging_Time_Hr'] = df['Charging_Time'].astype(str).str.extract(r'([\d.]+)').astype(float)

In [52]:
def split_tire(text):
    if pd.isna(text):
        return pd.Series([None, None])
    text = str(text)
    for tire in ['Tubeless', 'Tubed']:
        if text.startswith(tire):
            return pd.Series([tire, text[len(tire):].strip() or None])
    return pd.Series([None, text])

df[['Tire_Type_clean', 'Extra_Desc_1']] = df['Tire_Type'].apply(split_tire)

In [53]:
df.head()

,Product_Name,Brand,Bike_Type,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Maximum_Power,Range_KM,...,Charging_Time,Front_Brake,Tire_Type,Console_Type,Power_bhp,Power_kW,RPM,Charging_Time_Hr,Tire_Type_clean,Extra_Desc_1
0,Zest,TVS,Motorcycle,78550.0,4.5,359.0,38.0,109.7,NaN,NaN,...,NaN,Drum,TubelessUnder Seat Storage: 19 L,Analog SpeedometerWhile the Company has taken ...,NaN,NaN,NaN,NaN,Tubeless,Under Seat Storage: 19 L
1,Chetak C3503 Electric Scooter,Bajaj,Electric,124157.0,4.4,2178.0,210.0,NaN,NaN,151.0,...,5 hr,NaN,TubelessColoured LCD DisplayChetak offers a wa...,NaN,NaN,NaN,NaN,5.0,Tubeless,Coloured LCD DisplayChetak offers a warranty o...
2,Roadster,Yezdi,Motorcycle,214969.0,4.5,458.0,58.0,334.0,21.46 @7500 rpm,NaN,...,NaN,Disc,Tubeless,"Speedometer - LCD4 Years or 50,000 Km",NaN,NaN,7500,NaN,Tubeless,None
3,Scrambler,Yezdi,Motorcycle,200969.0,4.5,5032.0,486.0,334.0,22.05 kw@8100 r/min (30PS),NaN,...,NaN,Disc,Tubed,Speedometer - LCD,NaN,NaN,NaN,NaN,Tubed,None
4,XL100,TVS,Motorcycle,60480.0,4.5,458.0,58.0,99.7,NaN,NaN,...,NaN,Drum,Tubed,Analog,NaN,NaN,NaN,NaN,Tubed,None

In [54]:
df["Brand"].value_counts()

Brand
Hero             170
Other            124
Bajaj             91
Ather             70
TVS               63
VIDA              15
Suzuki             9
Royal Enfield      6
KTM                6
Yezdi              4
Name: count, dtype: int64

In [55]:
df["Product_Name"].value_counts()

Product_Name
Chetak C3503 Electric Scooter                      48
Xtreme                                             32
Splendor+ Non i3S                                  24
HF Deluxe Non i3S-Kick                             23
Chetak C3502 Electric Scooter                      23
                                                   ..
Amo Electric Bikes AMO Double Light Jaunty L LA     1
GIXXER SF Special Edition                           1
Green Invicta White 60KM                            1
Roadster                                            1
Oben Electric Rorr EZ 3.4kWh                        1
Name: count, Length: 173, dtype: int64

In [56]:
df[df['Brand'] == 'Other']['Product_Name'].unique()

array(['Kinetic Green E Luna X2', 'Kinetic Green E Luna X3',
       'Kinetic Green Zing', 'BGauss OOWAH EX',
       'Amo Electric Bikes Single Light LA', 'Joy e-bike Gen Next Nanu',
       'Joy e-bike Wolf +', 'Amo Electric Bikes Jaunty LA',
       'Green Sunny Blue 40KM', 'Lectrix Nduro 2.0', 'Revolt Motors RV1+',
       'Joy e-bike Mihos', 'Ampere Nexus ST Electric Scooter by Greaves',
       'Triumph Speed T4', 'Amo Electric Bikes Single Light LI',
       'Green Sunny Black 40KM', 'Jawa 42 FJ', 'Revolt Motors RV BlazeX',
       'Green Invicta Blue 60KM', 'Green Loader Black 80KM',
       'BGauss C12i MAX 2.0 Gen 2', 'Joy e-bike Wolf Eco',
       'Revolt Motors RV400', 'Amo Electric Bikes Jaunty S LI',
       'Revolt Motors RV400 BRZ', 'BGauss C12 MAX 2.0',
       'BGauss C12 MAX 3.0', 'Green Invicta White 60KM',
       'Amo Electric Bikes AMO Double Light Jaunty L LA',
       'Joy e-bike Gen Next Nanu +', 'Green Vista White 80KM',
       'BGauss C12i EX Gen 2', 'BGauss C12i MAX 3.0 Gen 2',
       'Amo Electric Bikes AMO Double Light Jaunty L LI',
       'BGauss OOWAH MAX', 'Simple One 5 kW', 'Simple OneS 3.7 kW',
       'Amo Electric Bikes AMO Feisty EV LA 12"', 'Motovolt MVS7',
       'Amo Electric Bikes Jaunty LI', 'Green Invicta Grey 80KM',
       'Green Vista Red 60KM', 'Green Falco White 60KM',
       'Green Invicta Black 80KM', 'Harley-Davidson X440 Vivid',
       'Green Sunny Blue 60KM', 'Green Vista Blue 60KM',
       'Amo Electric Bikes Jaunty 3W LA',
       'Amo Electric Bikes AMO Feisty EV LI 12"',
       'Ampere Nexus ST Electric Scooter by Greaves | 136 km IDC Range | 3.3 hr Fast Charging | Safest LFP Bat',
       'BGauss RUV350 MAX', 'Joy e-bike Gen Next Nanu Eco',
       'Green Falco Grey 60KM', 'Raptee.Hv T30', 'Green Elaan White 80KM',
       'Joy e-bike Wolf + )', 'Green Falco Black 80KM',
       'Amo Electric Bikes Jaunty 3W LI', 'Motovolt M7 Lite',
       'Triumph Thruxton 400', 'BGauss C12 iEX', 'Harley-Davidson X440 T',
       'Lectrix Zyro LA', 'BGauss BG C12i Max 2.0',
       'Oben Electric Rorr EZ 3.4kWh'], dtype=object)

In [57]:
known_brands = ['Hero', 'Bajaj', 'TVS', 'Ather', 'VIDA', 'Suzuki', 'KTM',
                 'Royal Enfield', 'Yezdi', 'Honda', 'Yamaha', 'Ola',
                 'Okinawa', 'Revolt', 'Ampere', 'Hero Electric', 'BGauss',
                 'Benelli', 'Jawa', 'Aprilia', 'Harley-Davidson', 'Triumph']

def extract_brand(row):
    name = str(row['Product_Name'])
    for b in sorted(known_brands, key=len, reverse=True):  # longer names first, e.g. "Royal Enfield" before "Royal"
        if name.startswith(b):
            return b
    return row['Brand']  # keep original if no match, don't blindly overwrite

df['Brand_fixed'] = df.apply(extract_brand, axis=1)
df['Brand_fixed'].value_counts()

Brand_fixed
Hero               165
Bajaj               91
Other               80
Ather               70
TVS                 63
BGauss              28
VIDA                20
Suzuki               9
Revolt               9
Royal Enfield        6
KTM                  6
Yezdi                4
Ampere               2
Triumph              2
Harley-Davidson      2
Jawa                 1
Name: count, dtype: int64

In [58]:
known_brands += ['Green', 'Amo Electric Bikes', 'Kinetic Green', 'Lectrix',
                  'Joy e-bike', 'BGauss', 'Motovolt', 'Simple', 'Oben Electric',
                  'Raptee.Hv']
df['Brand_fixed'] = df.apply(extract_brand, axis=1)
df['Brand_fixed'].value_counts()

Brand_fixed
Hero                  165
Bajaj                  91
Ather                  70
TVS                    63
BGauss                 28
Amo Electric Bikes     22
VIDA                   20
Kinetic Green          18
Green                  17
Joy e-bike             11
Suzuki                  9
Revolt                  9
Royal Enfield           6
KTM                     6
Motovolt                5
Yezdi                   4
Lectrix                 3
Ampere                  2
Triumph                 2
Simple                  2
Harley-Davidson         2
Jawa                    1
Raptee.Hv               1
Oben Electric           1
Name: count, dtype: int64

In [59]:
df.loc[df['Brand_fixed'].isin(['Ather', 'VIDA']), 'Bike_Type'] = 'Electric'

In [60]:
df[df['Brand_fixed']=='Ather'][['Product_Name','Engine_Capacity_CC','Range_KM','Bike_Type']].head(10)

,Product_Name,Engine_Capacity_CC,Range_KM,Bike_Type
12,Rizta S 123 KM,NaN,123.0,Electric
65,Rizta Z 123KM IDC Range,NaN,123.0,Electric
68,Rizta Z 161 KM IDC range with Stack Pro,NaN,161.0,Electric
69,Rizta Z 123KM IDC Range with Stack Pro,NaN,123.0,Electric
72,Rizta Z 161 KM IDC range with Stack Pro,NaN,161.0,Electric
73,Rizta Z 123KM IDC Range with Stack Pro,NaN,123.0,Electric
74,Rizta Z 161 KM IDC range with Stack Pro,NaN,161.0,Electric
75,Rizta Z 161 KM IDC range with Stack Pro,NaN,161.0,Electric
78,Rizta Z 161 KM IDC range,NaN,161.0,Electric
79,Rizta Z 123KM IDC Range,NaN,123.0,Electric

In [61]:
df['Bike_Type_fixed'] = df['Bike_Type']
df.loc[df['Engine_Capacity_CC'].notna(), 'Bike_Type_fixed'] = 'Motorcycle'
df.loc[df['Range_KM'].notna() & df['Engine_Capacity_CC'].isna(), 'Bike_Type_fixed'] = 'Electric'

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558 entries, 0 to 557
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product_Name        558 non-null    object
 1   Brand               558 non-null    object
 2   Bike_Type           558 non-null    object
 3   Price_INR           558 non-null    float64
 4   Rating              558 non-null    object
 5   Total_Ratings       558 non-null    float64
 6   Total_Reviews       558 non-null    float64
 7   Engine_Capacity_CC  263 non-null    float64
 8   Maximum_Power       218 non-null    object
 9   Range_KM            295 non-null    float64
 10  Maximum_Speed_KMPH  295 non-null    float64
 11  Charging_Time       295 non-null    object
 12  Front_Brake         263 non-null    object
 13  Tire_Type           526 non-null    object
 14  Console_Type        253 non-null    object
 15  Power_bhp           107 non-null    float64
 16  Power_kW            79 non-null     float64
 17  RPM                 113 non-null    object
 18  Charging_Time_Hr    295 non-null    float64
 19  Tire_Type_clean     526 non-null    object
 20  Extra_Desc_1        276 non-null    object
 21  Brand_fixed         558 non-null    object
 22  Bike_Type_fixed     558 non-null    object
dtypes: float64(9), object(14)
memory usage: 100.4+ KB

In [63]:
df.head()

,Product_Name,Brand,Bike_Type,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Maximum_Power,Range_KM,...,Tire_Type,Console_Type,Power_bhp,Power_kW,RPM,Charging_Time_Hr,Tire_Type_clean,Extra_Desc_1,Brand_fixed,Bike_Type_fixed
0,Zest,TVS,Motorcycle,78550.0,4.5,359.0,38.0,109.7,NaN,NaN,...,TubelessUnder Seat Storage: 19 L,Analog SpeedometerWhile the Company has taken ...,NaN,NaN,NaN,NaN,Tubeless,Under Seat Storage: 19 L,TVS,Motorcycle
1,Chetak C3503 Electric Scooter,Bajaj,Electric,124157.0,4.4,2178.0,210.0,NaN,NaN,151.0,...,TubelessColoured LCD DisplayChetak offers a wa...,NaN,NaN,NaN,NaN,5.0,Tubeless,Coloured LCD DisplayChetak offers a warranty o...,Bajaj,Electric
2,Roadster,Yezdi,Motorcycle,214969.0,4.5,458.0,58.0,334.0,21.46 @7500 rpm,NaN,...,Tubeless,"Speedometer - LCD4 Years or 50,000 Km",NaN,NaN,7500,NaN,Tubeless,None,Yezdi,Motorcycle
3,Scrambler,Yezdi,Motorcycle,200969.0,4.5,5032.0,486.0,334.0,22.05 kw@8100 r/min (30PS),NaN,...,Tubed,Speedometer - LCD,NaN,NaN,NaN,NaN,Tubed,None,Yezdi,Motorcycle
4,XL100,TVS,Motorcycle,60480.0,4.5,458.0,58.0,99.7,NaN,NaN,...,Tubed,Analog,NaN,NaN,NaN,NaN,Tubed,None,TVS,Motorcycle

In [64]:
df["Bike_Type_fixed"].value_counts()

Bike_Type_fixed
Electric      295
Motorcycle    263
Name: count, dtype: int64

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558 entries, 0 to 557
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product_Name        558 non-null    object
 1   Brand               558 non-null    object
 2   Bike_Type           558 non-null    object
 3   Price_INR           558 non-null    float64
 4   Rating              558 non-null    object
 5   Total_Ratings       558 non-null    float64
 6   Total_Reviews       558 non-null    float64
 7   Engine_Capacity_CC  263 non-null    float64
 8   Maximum_Power       218 non-null    object
 9   Range_KM            295 non-null    float64
 10  Maximum_Speed_KMPH  295 non-null    float64
 11  Charging_Time       295 non-null    object
 12  Front_Brake         263 non-null    object
 13  Tire_Type           526 non-null    object
 14  Console_Type        253 non-null    object
 15  Power_bhp           107 non-null    float64
 16  Power_kW            79 non-null     float64
 17  RPM                 113 non-null    object
 18  Charging_Time_Hr    295 non-null    float64
 19  Tire_Type_clean     526 non-null    object
 20  Extra_Desc_1        276 non-null    object
 21  Brand_fixed         558 non-null    object
 22  Bike_Type_fixed     558 non-null    object
dtypes: float64(9), object(14)
memory usage: 100.4+ KB

In [66]:
df["Bike_Type"].value_counts()

Bike_Type
Motorcycle    372
Electric      186
Name: count, dtype: int64

In [67]:
# See what values exist
print(df["Bike_Type_fixed"].value_counts())

# Boolean mask for electric bikes
electric_mask = df["Bike_Type_fixed"].str.strip().str.lower() == "electric"
print(f"Electric rows found: {electric_mask.sum()}")

Bike_Type_fixed
Electric      295
Motorcycle    263
Name: count, dtype: int64
Electric rows found: 295

In [68]:
# Keep only non-electric bikes (motorcycles, scooters, etc.)
df_non_electric = df[~electric_mask].reset_index(drop=True)

print(df.shape, "->", df_non_electric.shape)

(558, 23) -> (263, 23)

In [69]:
df_non_electric.head()

,Product_Name,Brand,Bike_Type,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Maximum_Power,Range_KM,...,Tire_Type,Console_Type,Power_bhp,Power_kW,RPM,Charging_Time_Hr,Tire_Type_clean,Extra_Desc_1,Brand_fixed,Bike_Type_fixed
0,Zest,TVS,Motorcycle,78550.0,4.5,359.0,38.0,109.7,NaN,NaN,...,TubelessUnder Seat Storage: 19 L,Analog SpeedometerWhile the Company has taken ...,NaN,NaN,NaN,NaN,Tubeless,Under Seat Storage: 19 L,TVS,Motorcycle
1,Roadster,Yezdi,Motorcycle,214969.0,4.5,458.0,58.0,334.0,21.46 @7500 rpm,NaN,...,Tubeless,"Speedometer - LCD4 Years or 50,000 Km",NaN,NaN,7500,NaN,Tubeless,None,Yezdi,Motorcycle
2,Scrambler,Yezdi,Motorcycle,200969.0,4.5,5032.0,486.0,334.0,22.05 kw@8100 r/min (30PS),NaN,...,Tubed,Speedometer - LCD,NaN,NaN,NaN,NaN,Tubed,None,Yezdi,Motorcycle
3,XL100,TVS,Motorcycle,60480.0,4.5,458.0,58.0,99.7,NaN,NaN,...,Tubed,Analog,NaN,NaN,NaN,NaN,Tubed,None,TVS,Motorcycle
4,Pleasure+ 110 VX,Hero,Motorcycle,67276.0,4.7,1632.0,218.0,110.9,NaN,NaN,...,TubelessUnder Seat Storage: 14 L,SpeedometerHero MotoCorp warrants all its moto...,NaN,NaN,NaN,NaN,Tubeless,Under Seat Storage: 14 L,Hero,Motorcycle

In [70]:
df_non_electric.columns

Index(['Product_Name', 'Brand', 'Bike_Type', 'Price_INR', 'Rating',
       'Total_Ratings', 'Total_Reviews', 'Engine_Capacity_CC', 'Maximum_Power',
       'Range_KM', 'Maximum_Speed_KMPH', 'Charging_Time', 'Front_Brake',
       'Tire_Type', 'Console_Type', 'Power_bhp', 'Power_kW', 'RPM',
       'Charging_Time_Hr', 'Tire_Type_clean', 'Extra_Desc_1', 'Brand_fixed',
       'Bike_Type_fixed'],
      dtype='object')

In [71]:
df_non_electric.drop(['Brand',"Bike_Type",'Range_KM','Maximum_Speed_KMPH','Charging_Time','Tire_Type',
                        'Power_kW',"Power_bhp","Charging_Time_Hr"],axis=1,inplace=True)

In [72]:
df_non_electric.columns

Index(['Product_Name', 'Price_INR', 'Rating', 'Total_Ratings', 'Total_Reviews',
       'Engine_Capacity_CC', 'Maximum_Power', 'Front_Brake', 'Console_Type',
       'RPM', 'Tire_Type_clean', 'Extra_Desc_1', 'Brand_fixed',
       'Bike_Type_fixed'],
      dtype='object')

In [73]:
df_non_electric.head()

,Product_Name,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Maximum_Power,Front_Brake,Console_Type,RPM,Tire_Type_clean,Extra_Desc_1,Brand_fixed,Bike_Type_fixed
0,Zest,78550.0,4.5,359.0,38.0,109.7,NaN,Drum,Analog SpeedometerWhile the Company has taken ...,NaN,Tubeless,Under Seat Storage: 19 L,TVS,Motorcycle
1,Roadster,214969.0,4.5,458.0,58.0,334.0,21.46 @7500 rpm,Disc,"Speedometer - LCD4 Years or 50,000 Km",7500,Tubeless,None,Yezdi,Motorcycle
2,Scrambler,200969.0,4.5,5032.0,486.0,334.0,22.05 kw@8100 r/min (30PS),Disc,Speedometer - LCD,NaN,Tubed,None,Yezdi,Motorcycle
3,XL100,60480.0,4.5,458.0,58.0,99.7,NaN,Drum,Analog,NaN,Tubed,None,TVS,Motorcycle
4,Pleasure+ 110 VX,67276.0,4.7,1632.0,218.0,110.9,NaN,Drum,SpeedometerHero MotoCorp warrants all its moto...,NaN,Tubeless,Under Seat Storage: 14 L,Hero,Motorcycle

In [74]:
df_non_electric["Maximum_Power"].isnull().sum()

45

In [75]:
df_non_electric["RPM"].isnull().sum()

150

In [76]:
import numpy as np

In [77]:
def convert_to_bhp(power):

    if pd.isna(power):
        return np.nan

    text = str(power).lower()

    # ----------- BHP -----------
    bhp = re.search(r'(\d+\.?\d*)\s*bhp', text)
    if bhp:
        return float(bhp.group(1))

    # ----------- PS -----------
    ps = re.search(r'(\d+\.?\d*)\s*ps', text)
    if ps:
        return round(float(ps.group(1)) * 0.98632, 2)

    # ----------- kW -----------
    kw = re.search(r'(\d+\.?\d*)\s*kw', text)
    if kw:
        return round(float(kw.group(1)) * 1.34102, 2)

    # ----------- Only Number -----------
    num = re.search(r'(\d+\.?\d*)', text)
    if num:
        return float(num.group(1))

    return np.nan

In [78]:
df_non_electric["Maximum_Power_BHP"] = (
    df_non_electric["Maximum_Power"]
    .apply(convert_to_bhp)
)

In [79]:
df_non_electric[
    ["Maximum_Power", "Maximum_Power_BHP"]
].head(20)

                    Maximum_Power  Maximum_Power_BHP
0                             NaN                NaN
1                 21.46 @7500 rpm              21.46
2      22.05 kw@8100 r/min (30PS)              29.59
3                             NaN                NaN
4                             NaN                NaN
5                             NaN                NaN
6   15.01 kW (20.4 PS) @ 7750 rpm              20.12
7            8.18 bhp @ 7,350 rpm               8.18
8            8.18 bhp @ 7,350 rpm               8.18
9               5.9 kW @ 8000 rpm               7.91
10   8.68 kW (11.8 PS) @ 8500 rpm              11.64
11         8.18 bhp (at 7350 RPM)               8.18
12             8.18 bhp @7350 RPM               8.18
13         8.18 bhp (at 7350 RPM)               8.18
14              5.9 kW @ 8000 rpm               7.91
15         8.18 bhp (at 7350 RPM)               8.18
16              5.9 kW @ 8000 rpm               7.91
17              5.9 kW @ 8000 rpm               7.91
18     22.05 kw@8100 r/min (30PS)              29.59
19                           7.91               7.91

In [80]:
df_non_electric.drop(columns=["Maximum_Power"], inplace=True)

In [81]:
df_non_electric.columns

Index(['Product_Name', 'Price_INR', 'Rating', 'Total_Ratings', 'Total_Reviews',
       'Engine_Capacity_CC', 'Front_Brake', 'Console_Type', 'RPM',
       'Tire_Type_clean', 'Extra_Desc_1', 'Brand_fixed', 'Bike_Type_fixed',
       'Maximum_Power_BHP'],
      dtype='object')

In [82]:
df_non_electric.head()

,Product_Name,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Front_Brake,Console_Type,RPM,Tire_Type_clean,Extra_Desc_1,Brand_fixed,Bike_Type_fixed,Maximum_Power_BHP
0,Zest,78550.0,4.5,359.0,38.0,109.7,Drum,Analog SpeedometerWhile the Company has taken ...,NaN,Tubeless,Under Seat Storage: 19 L,TVS,Motorcycle,NaN
1,Roadster,214969.0,4.5,458.0,58.0,334.0,Disc,"Speedometer - LCD4 Years or 50,000 Km",7500,Tubeless,None,Yezdi,Motorcycle,21.46
2,Scrambler,200969.0,4.5,5032.0,486.0,334.0,Disc,Speedometer - LCD,NaN,Tubed,None,Yezdi,Motorcycle,29.59
3,XL100,60480.0,4.5,458.0,58.0,99.7,Drum,Analog,NaN,Tubed,None,TVS,Motorcycle,NaN
4,Pleasure+ 110 VX,67276.0,4.7,1632.0,218.0,110.9,Drum,SpeedometerHero MotoCorp warrants all its moto...,NaN,Tubeless,Under Seat Storage: 14 L,Hero,Motorcycle,NaN

In [ ]:
df_non_electric=df

# Exploring Data Analysis

In [172]:
df_non_electric.head()

,Product_Name,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Front_Brake,Console_Type,RPM,Tire_Type_clean,Extra_Desc_1,Brand_fixed,Bike_Type_fixed,Maximum_Power_BHP
0,Zest,78550.0,4.5,359.0,38.0,109.7,Drum,Analog SpeedometerWhile the Company has taken ...,NaN,Tubeless,Under Seat Storage: 19 L,TVS,Motorcycle,NaN
1,Roadster,214969.0,4.5,458.0,58.0,334.0,Disc,"Speedometer - LCD4 Years or 50,000 Km",7500,Tubeless,None,Yezdi,Motorcycle,21.46
2,Scrambler,200969.0,4.5,5032.0,486.0,334.0,Disc,Speedometer - LCD,NaN,Tubed,None,Yezdi,Motorcycle,29.59
3,XL100,60480.0,4.5,458.0,58.0,99.7,Drum,Analog,NaN,Tubed,None,TVS,Motorcycle,NaN
4,Pleasure+ 110 VX,67276.0,4.7,1632.0,218.0,110.9,Drum,SpeedometerHero MotoCorp warrants all its moto...,NaN,Tubeless,Under Seat Storage: 14 L,Hero,Motorcycle,NaN

In [176]:
df_non_electric.tail()

,Product_Name,Price_INR,Rating,Total_Ratings,Total_Reviews,Engine_Capacity_CC,Front_Brake,Console_Type,RPM,Tire_Type_clean,Extra_Desc_1,Brand_fixed,Bike_Type_fixed,Maximum_Power_BHP
258,PULSAR 125 -NEON DISC LED,89571.0,5,237.0,61.0,124.38,Disc,Fully Digital Reverse Monochrome LCDBajaj Auto...,8500,Tubeless,None,Bajaj,Motorcycle,11.64
259,Radeon,77950.0,4.4,38.0,10.0,109.70,Drum,Speedometer: Analogue Odometer: Digital,NaN,Tubeless,None,TVS,Motorcycle,8.18
260,N160 USD Split Seat,127175.0,4.4,53.0,14.0,164.82,Disc,Bluetooth Connected Digital Console with Call ...,NaN,Tubeless,None,Bajaj,Motorcycle,15.78
261,Xoom 125 ZX,92783.0,4.4,6.0,1.0,124.60,Disc,Digital MeterHero MotoCorp warrants all its mo...,NaN,Tubeless,None,Hero,Motorcycle,NaN
262,Splendor+ Non i3S,77349.0,4.5,237.0,61.0,97.20,Drum,Analogue speedometerHero MotoCorp warrants all...,8000,Tubeless,None,Hero,Motorcycle,7.91

In [180]:
df_non_electric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product_Name        263 non-null    object
 1   Price_INR           263 non-null    float64
 2   Rating              263 non-null    object
 3   Total_Ratings       263 non-null    float64
 4   Total_Reviews       263 non-null    float64
 5   Engine_Capacity_CC  263 non-null    float64
 6   Front_Brake         263 non-null    object
 7   Console_Type        253 non-null    object
 8   RPM                 113 non-null    object
 9   Tire_Type_clean     263 non-null    object
 10  Extra_Desc_1        20 non-null     object
 11  Brand_fixed         263 non-null    object
 12  Bike_Type_fixed     263 non-null    object
 13  Maximum_Power_BHP   218 non-null    float64
dtypes: float64(5), object(9)
memory usage: 28.9+ KB